### ISSUE TITLE
Fail displaying text on result card.

### ISSUE THREAD

**Issue by DominikBerger01** [londonappbrewery/BMI-Calculator-Flutter-Completed#3]
The text in the result page is not changing it always shows one scenario, compared the code and I find no issues. Funny enough sometimes I encountered that it changes after cold restart without changes to the code, but only once.
Please help. 

`import 'dart:math';

class BMICalculator {
  BMICalculator({this.weight, this.height});

  final int weight;
  final int height;
  double _bmi = 0.0;

  String calcBMINumber() {
    double _bmi = weight / pow(height / 100, 2);
    return _bmi.toStringAsFixed(1);
  }

  String showResultText() {
    if (_bmi >= 25.0) {
      return 'Fat';
    } else if (_bmi >= 18.5) {
      return 'Normal';
    } else {
      return 'Beanstick';
    }
  }

  String showSuggestionText() {
    if (_bmi >= 25.0) {
      return 'Damn you are fucking fat';
    } else if (_bmi >= 18.5) {
      return 'You seem to be quite normal';
    } else {
      return 'You skinny piece of shit!';
    }
  }
}
`

**Comment by lorrainemutheu** [comment]
`import 'dart:math';

class CalculateBrain{
  final int height;
  final int weight;
  double _bmi;

  CalculateBrain({this.height,this.weight});

  String bmiCalculate(){
      return bmi().toStringAsFixed(1);
  }

  double bmi(){
    _bmi = weight / pow(height/100, 2);
    return _bmi;
  }


  String getResult(){
    if(bmi() >= 25){
      return 'OverWeight';
    }else if(bmi() >= 18.5){
      return 'Normal';
    }else{
      return 'UnderWeight';
    }
  }

  String getInterpretation(){
    if(bmi() >= 25){
      return 'You have higher than normal body weight. Try to exercise more.';
    }else if(bmi() >= 18.5){
      return 'You have a normal body weight. Good job!';
    }else{
      return 'You have a lower than normal body weight. You can eat a bit more.';
    }
  }
}`

I made the following changes as shown above and it worked. 
The reason why the text in the result does not change is because the your value of _bmi was intialised to zero so the value of the bmi is always zero. The calculated value of the _bmi is inside a function and thus not accessible by the other functions. 
I have used the function of the calculated BMI as the value of comparison in the other functions, hence the result.

**Comment by DominikBerger01** [comment]
Thank you very much, works now !
